### ISSUE TITLE
Packing app on Windows!

### ISSUE THREAD

**Issue by hoangdung-qbt** [DigitalStrawberry/ANE-StoreReview#1]
Does this extension work well (on mobile devices) if I packed app on Windows OS or I need to pack app on MacOS with Xcode installed? Thanks!

**Comment by marpies** [comment]
We had published the ANE before AIR SDK was built with iOS 10 SDK, that's why we had to use the Xcode SDK to package the app. You should be able to package your app on Windows if you use AIR 28, though it may work with AIR 26 or 27 as well. As long as you're able to package your IPA without errors then the extension should work fine.

**Comment by hoangdung-qbt** [comment]
Thanks for your reply. Your premium feather themes also look good, I will try it if having a chance. Cheers!

**Comment by marpies** [comment]
Thanks! Feel free to reopen this issue if you encounter any problems when packaging your app.
